# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosFlixApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosFlixApp
  pod 'AFNetworking'

  target 'iosFlixAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosFlixAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
